name: Security Audit

on:
  pull_request:
    paths: ['**/Cargo.toml', '**/Cargo.lock']
  push:
    branches: [main]
    paths: ['**/Cargo.toml', '**/Cargo.lock']
  schedule:
    - cron: '23 5 * * *'

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install cargo audit
        run: cargo install cargo-audit
      - name: Run cargo audit
        run: cargo audit
