name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  RUSTFLAGS: -Dwarnings

jobs:
  build_and_test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest]
        rust: [stable, beta]

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        profile: minimal
        override: true

    - uses: Swatinem/rust-cache@v1

    - run: cargo fetch
    - run: cargo check --all --examples
    - run: cargo test --all

  check_fmt_and_docs:
    name: Checking fmt, clippy, and docs
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy

    - uses: Swatinem/rust-cache@v1

    - run: cargo check
    - run: cargo clippy --tests --examples -- -D warnings
    - run: cargo fmt --all -- --check
    - run: cargo doc --no-deps
